name: Lazarus Build for Windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Lazarus
        uses: gcarreno/setup-lazarus@v3
        with:
          lazarus-version: stable

      - name: Build Lazarus Project
        run: |
          lazbuild --cpu=x86_64 --os=win64 SumAntiReversi8x8.lpi

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Windows Build
          path: |
            *.exe
            *.dll
            bin/
